// STORE CONSTANTS

export const USER_CONSTANTS = {
  REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
  REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
  REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  GETALL_REQUEST: 'USERS_GETALL_REQUEST',
  GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
  GETALL_FAILURE: 'USERS_GETALL_FAILURE',

  DELETE_REQUEST: 'USERS_DELETE_REQUEST',
  DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
  DELETE_FAILURE: 'USERS_DELETE_FAILURE',
};

export const PRODUCT_CONSTANTS = {
  GETALL: 'GETALL_PRODUCTS',
  FILTERED_PRODUCTS: 'FILTERED_PRODUCTS',
  SPINNER: 'SPINNER',
};

export const ORDER_CONSTANTS = {
  ORDER: 'ORDER',
};

export const CART_CONSTANTS = {
  ADDCART: 'ADD_CART',
  REMOVECART: 'REMOVE_CART',
  CLEARCART: 'CLEARCART',
  UPDATECART: 'UPDATECART',
};

export const ALERT_CONSTANTS = {
  SUCCESS: 'ALERT_SUCCESS',
  ERROR: 'ALERT_ERROR',
  CLEAR: 'ALERT_CLEAR',
  INFO: 'ALERT_INFORMATION',
};

export const ADDRESS_CONSTANTS = {
  ADDADDRESS: 'ADDADDRESS',
  DELIVERYADDRESS: 'DELIVERYADDRESS',
};
